branches:
  only:
    - master
    - equiv_atoms
    - joseph
dist: xenial
language: python
python:
  - "3.7"
install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda config --append channels conda-forge
  - conda info -a
  - conda create -q -n test-env python=$TRAVIS_PYTHON_VERSION --file requirements.txt
  - source activate test-env
  - python setup.py install
script:
  - python -m pytest tests/
  - python -m pytest --cov-report term --cov autode tests/
after_success:
  - codecov